name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          server-id: central
          server-username: ${{ secrets.MAVEN_USER }}
          server-password: ${{ secrets.MAVEN_TOKEN }}
      - name: Maven deploy
        run: maven deploy
