name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          server-id: central
          server-username: ${{ secrets.MAVEN_USER }}--- central-publishing-maven-plugin:0.8.0:publish
          server-password: ${{ secrets.MAVEN_TOKEN }}
      - name: Maven publish
        run: |
          mvn clean install
          mvn org.sonatype.central:central-publishing-maven-plugin:publish
